export enum PayrollStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  WAITING_MANAGER_APPROVAL = 'WAITING_MANAGER_APPROVAL',
  WAITING_FINANCE_APPROVAL = 'WAITING_FINANCE_APPROVAL',
  APPROVED = 'APPROVED',
  FROZEN = 'FROZEN',
  PAID = 'PAID',
}
